apiVersion: v1
kind: Pod
metadata:
  name: bin2dec-pod-1
  labels:
    app: bin2dec-app
spec:
  containers:
    - name: bin2dec-container
      image: petersonmarcelo/bin2dec-api:v1.0
      ports:
        - containerPort: 8080